import { sidebar } from "vuepress-theme-hope";

export const zhSidebar = sidebar({
  "/zh/expression/": [
    { text: "Intro", icon: "creative", prefix: "Intro/", collapsable: true, children: "structure" },
    { text: "General", icon: "creative", prefix: "General/", collapsable: true, children: "structure" },
    { text: "Objects", icon: "creative", prefix: "Objects/", collapsable: true, children: "structure" },
    { text: "Layers", icon: "creative", prefix: "Layers/", collapsable: true, children: "structure" },
    { text: "Text", icon: "creative", prefix: "Text/", collapsable: true, children: "structure" },
  ],
  "/zh/effects/": [
    { text: "Overview", icon: "creative", prefix: "Overview/", collapsable: true, children: "structure" },
    { text: "3D-Channel", icon: "creative", prefix: "3D-Channel/", collapsable: true, children: "structure" },
    { text: "Audio", icon: "creative", prefix: "Audio/", collapsable: true, children: "structure" },
    { text: "Blur-Sharpen", icon: "creative", prefix: "Blur-Sharpen/", collapsable: true, children: "structure" },
    { text: "Channel", icon: "creative", prefix: "Channel/", collapsable: true, children: "structure" },
    { text: "Color-Correction", icon: "creative", prefix: "Color-Correction/", collapsable: true, children: "structure" },
    { text: "Distort", icon: "creative", prefix: "Distort/", collapsable: true, children: "structure" },
    { text: "Expression-Controls", icon: "creative", prefix: "Expression-Controls/", collapsable: true, children: "structure" },
    { text: "Generate", icon: "creative", prefix: "Generate/", collapsable: true, children: "structure" },
    { text: "Immersive-Video", icon: "creative", prefix: "Immersive-Video/", collapsable: true, children: "structure" },
    { text: "Keying", icon: "creative", prefix: "Keying/", collapsable: true, children: "structure" },
    { text: "Matte", icon: "creative", prefix: "Matte/", collapsable: true, children: "structure" },
    { text: "Noise-Grain", icon: "creative", prefix: "Noise-Grain/", collapsable: true, children: "structure" },
    { text: "Obsolete", icon: "creative", prefix: "Obsolete/", collapsable: true, children: "structure" },
    { text: "Perspective", icon: "creative", prefix: "Perspective/", collapsable: true, children: "structure" },
    { text: "Simulation", icon: "creative", prefix: "Simulation/", collapsable: true, children: "structure" },
    { text: "Stylize", icon: "creative", prefix: "Stylize/", collapsable: true, children: "structure" },
    { text: "Text", icon: "creative", prefix: "Text/", collapsable: true, children: "structure" },
    { text: "Time", icon: "creative", prefix: "Time/", collapsable: true, children: "structure" },
    { text: "Transition", icon: "creative", prefix: "Transition/", collapsable: true, children: "structure" },
    { text: "Utility", icon: "creative", prefix: "Utility/", collapsable: true, children: "structure" },
  ],
  "/zh/shape/": "structure",
  "/zh/text-animation/": "structure",
  "/zh/scripting/": [
    { text: "学习指南", icon: "creative", prefix: "Guide/", collapsable: true, children: "structure" },
    { text: "介绍", icon: "creative", prefix: "Intro/", collapsable: true, children: "structure" },
    { text: "常规", icon: "creative", prefix: "General/", collapsable: true, children: "structure" },
    { text: "项目 Item", icon: "creative", prefix: "Item/", collapsable: true, children: "structure" },
    { text: "图层 Layer", icon: "creative", prefix: "Layer/", collapsable: true, children: "structure" },
    { text: "属性 Property", icon: "creative", prefix: "Property/", collapsable: true, children: "structure" },
    { text: "渲染队列 Render-Queue", icon: "creative", prefix: "Render-Queue/", collapsable: true, children: "structure" },
    { text: "图层源 Source", icon: "creative", prefix: "Source/", collapsable: true, children: "structure" },
    { text: "其他 Other", icon: "creative", prefix: "Other/", collapsable: true, children: "structure" },
    { text: "匹配名称 Match-Name", icon: "creative", prefix: "Match-Name/", collapsable: true, children: "structure" },
    { text: "Javascript-工具", icon: "creative", prefix: "Javascript-Tools/", collapsable: true, children: "structure" },
    { text: "第三方工具", icon: "creative", prefix: "Third-Part/", collapsable: true, children: "structure" },
  ],
  "/zh/plugins/stardust/": [
    { text: "介绍", icon: "creative", prefix: "Overview/", collapsable: true, children: "structure" },
    { text: "交互式界面", icon: "creative", prefix: "User-Interface/", collapsable: true, children: "structure" },
    { text: "发射器", icon: "creative", prefix: "Emitters/", collapsable: true, children: "structure" },
    { text: "粒子", icon: "creative", prefix: "Particle/", collapsable: true, children: "structure" },
    { text: "场", icon: "creative", prefix: "Space-Deformers/", collapsable: true, children: "structure" },
    { text: "模型与材质", icon: "creative", prefix: "Model-And-Materials/", collapsable: true, children: "structure" },
    { text: "体积", icon: "creative", prefix: "Volumes/", collapsable: true, children: "structure" },
    { text: "变形与变换", icon: "creative", prefix: "Transform/", collapsable: true, children: "structure" },
  ]
});
