import { sidebar } from "vuepress-theme-hope";

export const enSidebar = sidebar({
  "/en/": [
    "",
    "home",
    "slides",
  ],
  "/en/ae/expression/": [
    { text: "Intro", icon: "creative", prefix: "Intro/", collapsable: true, children: "structure" },
    { text: "General", icon: "creative", prefix: "General/", collapsable: true, children: "structure" },
    { text: "Objects", icon: "creative", prefix: "Objects/", collapsable: true, children: "structure" },
    { text: "Layers", icon: "creative", prefix: "Layers/", collapsable: true, children: "structure" },
    { text: "Text", icon: "creative", prefix: "Text/", collapsable: true, children: "structure" },
  ],
  "/en/ae/scripting/": [

    { text: "Intro", icon: "creative", prefix: "Intro/", collapsable: true, children: "structure" },
    { text: "General", icon: "creative", prefix: "General/", collapsable: true, children: "structure" },
    { text: "Item", icon: "creative", prefix: "Item/", collapsable: true, children: "structure" },
    { text: "Layer", icon: "creative", prefix: "Layer/", collapsable: true, children: "structure" },
    { text: "Property", icon: "creative", prefix: "Property/", collapsable: true, children: "structure" },
    { text: "Render-Queue", icon: "creative", prefix: "Render-Queue/", collapsable: true, children: "structure" },
    { text: "Source", icon: "creative", prefix: "Source/", collapsable: true, children: "structure" },
    { text: "Other", icon: "creative", prefix: "Other/", collapsable: true, children: "structure" },
    { text: "Match-Name", icon: "creative", prefix: "Match-Name/", collapsable: true, children: "structure" },
  ],
  "/en/houdini/vex/": [
    { text: "Arrays", icon: "creative", prefix: "Arrays/", collapsable: true, children: "structure" },
    { text: "Attributes-And-Intrinsics", icon: "creative", prefix: "Attributes-And-Intrinsics/", collapsable: true, children: "structure" },
    { text: "Bsdfs", icon: "creative", prefix: "Bsdfs/", collapsable: true, children: "structure" },
    { text: "Chop", icon: "creative", prefix: "Chop/", collapsable: true, children: "structure" },
    { text: "Color", icon: "creative", prefix: "Color/", collapsable: true, children: "structure" },
    { text: "Conversion", icon: "creative", prefix: "Conversion/", collapsable: true, children: "structure" },
    { text: "Crowds", icon: "creative", prefix: "Crowds/", collapsable: true, children: "structure" },
    { text: "Dict", icon: "creative", prefix: "Dict/", collapsable: true, children: "structure" },
    { text: "Displace", icon: "creative", prefix: "Displace/", collapsable: true, children: "structure" },
    { text: "File-I-O", icon: "creative", prefix: "File-I-O/", collapsable: true, children: "structure" },
    { text: "Filter", icon: "creative", prefix: "Filter/", collapsable: true, children: "structure" },
    { text: "Fuzzy-Logic", icon: "creative", prefix: "Fuzzy-Logic/", collapsable: true, children: "structure" },
    { text: "Geometry", icon: "creative", prefix: "Geometry/", collapsable: true, children: "structure" },
    { text: "Groups", icon: "creative", prefix: "Groups/", collapsable: true, children: "structure" },
    { text: "Half-Edges", icon: "creative", prefix: "Half-Edges/", collapsable: true, children: "structure" },
    { text: "Image-Processing", icon: "creative", prefix: "Image-Processing/", collapsable: true, children: "structure" },
    { text: "Interpolation", icon: "creative", prefix: "Interpolation/", collapsable: true, children: "structure" },
    { text: "Light", icon: "creative", prefix: "Light/", collapsable: true, children: "structure" },
    { text: "Math", icon: "creative", prefix: "Math/", collapsable: true, children: "structure" },
    { text: "Measure", icon: "creative", prefix: "Measure/", collapsable: true, children: "structure" },
    { text: "Metaball", icon: "creative", prefix: "Metaball/", collapsable: true, children: "structure" },
    { text: "Nodes", icon: "creative", prefix: "Nodes/", collapsable: true, children: "structure" },
    { text: "Noise-And-Randomness", icon: "creative", prefix: "Noise-And-Randomness/", collapsable: true, children: "structure" },
    { text: "Normals", icon: "creative", prefix: "Normals/", collapsable: true, children: "structure" },
    { text: "Open-Color-Io", icon: "creative", prefix: "Open-Color-Io/", collapsable: true, children: "structure" },
    { text: "Particles", icon: "creative", prefix: "Particles/", collapsable: true, children: "structure" },
    { text: "Point-Clouds-And-3D-Images", icon: "creative", prefix: "Point-Clouds-And-3D-Images/", collapsable: true, children: "structure" },
    { text: "Sampling", icon: "creative", prefix: "Sampling/", collapsable: true, children: "structure" },
    { text: "Sensor-Input", icon: "creative", prefix: "Sensor-Input/", collapsable: true, children: "structure" },
    { text: "Shading-And-Rendering", icon: "creative", prefix: "Shading-And-Rendering/", collapsable: true, children: "structure" },
    { text: "Strings", icon: "creative", prefix: "Strings/", collapsable: true, children: "structure" },
    { text: "Subdivision-Surfaces", icon: "creative", prefix: "Subdivision-Surfaces/", collapsable: true, children: "structure" },
    { text: "Tetrahedrons", icon: "creative", prefix: "Tetrahedrons/", collapsable: true, children: "structure" },
    { text: "Texturing", icon: "creative", prefix: "Texturing/", collapsable: true, children: "structure" },
    { text: "Transforms-And-Space", icon: "creative", prefix: "Transforms-And-Space/", collapsable: true, children: "structure" },
    { text: "Usd", icon: "creative", prefix: "Usd/", collapsable: true, children: "structure" },
    { text: "Utility", icon: "creative", prefix: "Utility/", collapsable: true, children: "structure" },
    { text: "Volume", icon: "creative", prefix: "Volume/", collapsable: true, children: "structure" },
  ],
});
